modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/Daomephsta/DangerSense/issues"
[[mods]]
modId="dangersense"
version="${file.jarVersion}"
displayName="DangerSense"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dangersense"
authors="Daomephsta"
description="Adds an item for detecting nearby hostile mobs"
logoFile="logo.png"
[[dependencies.dangersense]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
